version: '3.8'

services: 
  pgdb:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
  mongodb:
    image: bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USERNAME=docker
      - MONGODB_PASSWORD=docker
      - MONGODB_DATABASE=mongodb